name: osm_location_picker
description: "A self-contained Flutter location picker powered by OpenStreetMap. No API key required. Supports address search, GPS, and full theming."
version: 1.0.4

repository: https://github.com/ahmedalam782/osm_location_picker
homepage: https://github.com/ahmedalam782/osm_location_picker

topics:
  - map
  - location
  - geocoding
  - openstreetmap
  - gps

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  dio: ^5.11.1
  flutter_svg: ^2.3.0
  lottie: ^3.6.1
  internet_connection_checker_plus: ^3.1.2
  geolocator: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
